# 基础响应格式规则

def base_response(result=1, success=True, msg='', code='LAN_SUS-0', data=None):
    """
    基础响应格式
    
    Args:
        result: 处理结果，1成功，0失败
        success: 操作结果，true成功，false无效
        msg: 返回信息，通常为错误信息
        code: 返回码，正常操作统一返回码，异常操作单独返回码
        data: 业务数据，数值、字符串、对象或集合等
        
    Returns:
        dict: 标准化的响应格式
    """
    return {
        'result': result,
        'success': success,
        'msg': msg,
        'code': code,
        'data': data or ''
    }

# 错误码定义
ERROR_CODES = {
    'PASSWORD_ERROR': 'LAN_EXP-1001',
    'PASSWORD_EMPTY': 'LAN_EXP-1001',
    'PASS_PARAM_ERROR': 'LAN_EXP-1002',
    'PASSWORD_NOT_SET': 'LAN_EXP-1003',
    'DEVICE_DISABLED': 'LAN_EXP-1004',
    'DEVICE_BUSY': 'LAN_EXP-1005',
    'METHOD_NOT_SUPPORTED': 'LAN_EXP-1006',
    'OLD_PASSWORD_ERROR': 'LAN_EXP-2001',
    'NEW_PASSWORD_ERROR': 'LAN_EXP-2002',
    'PASSWORD_CANT_BE_EMPTY': 'LAN_EXP-2003',
    'NEW_PASSWORD_CANT_BE_EMPTY': 'LAN_EXP-2004',
    'PASSWORD_INCORRECT': 'LAN_EXP-2005',
    'INIT_PASSWORD_SAME': 'LAN_EXP-2006',
    'CONFIG_PARAM_ERROR': 'LAN_EXP-2007',
    'CONFIG_EMPTY': 'LAN_EXP-2013',
    'CONFIG_JSON_ERROR': 'LAN_EXP-2008',
    'CONFIG_ILLEGAL': 'LAN_EXP-2009',
    'INPUT_NO_PARAM_ERROR': 'LAN_EXP-2208',
    'INPUT_NO_ILLEGAL': 'LAN_EXP-2209',
    'IS_ENABLE_PARAM_ERROR': 'LAN_EXP-2210',
    'IS_ENABLE_ILLEGAL': 'LAN_EXP-2211',
    'TYPE_PARAM_ERROR': 'LAN_EXP-2212',
    'TYPE_ILLEGAL': 'LAN_EXP-2213',
    'NAME_ILLEGAL': 'LAN_EXP-2214',
    'CALLBACK_URL_PARAM_ERROR': 'LAN_EXP-2063',
    'CALLBACK_URL_ILLEGAL': 'LAN_EXP-2099',
    'URL_PARAM_ERROR': 'LAN_EXP-2061',
    'URL_ILLEGAL': 'LAN_EXP-2064',
    'LANGUAGE_TYPE_PARAM_ERROR': 'LAN_EXP-2188',
    'LANGUAGE_TYPE_ILLEGAL': 'LAN_EXP-2189',
    'TIMEZONE_PARAM_ERROR': 'LAN_EXP-2201',
    'TIMEZONE_ILLEGAL': 'LAN_EXP-2200',
    'TIMESTAMP_PARAM_ERROR': 'LAN_EXP-2049',
    'TIMESTAMP_FORMAT_ERROR': 'LAN_EXP-2050',
    'PERSON_PARAM_ERROR': 'LAN_EXP-3001',
    'PERSON_JSON_ERROR': 'LAN_EXP-3002',
    'PERSON_ID_ILLEGAL': 'LAN_EXP-3003',
    'NAME_EMPTY': 'LAN_EXP-3004',
    'PERSON_ID_EXISTS': 'LAN_EXP-3005',
    'PERSON_ID_NOT_EXISTS': 'LAN_EXP-3009',
    'PERSON_ID_PARAM_ERROR': 'LAN_EXP-3007',
    'PERSON_ID_EMPTY': 'LAN_EXP-3008',
    'PERSON_COUNT_TOO_MANY': 'LAN_EXP-3040',
    'PERSON_ID_PAGINATION_ERROR': 'LAN_EXP-3015',
    'PERSON_ID_PAGINATION_EMPTY': 'LAN_EXP-3016',
    'PERSON_ID_PAGINATION_ILLEGAL': 'LAN_EXP-3017',
    'LENGTH_ILLEGAL': 'LAN_EXP-3018',
    'INDEX_ILLEGAL': 'LAN_EXP-3019',
    'FACE_ID_PARAM_ERROR': 'LAN_EXP-4002',
    'IMG_BASE64_PARAM_ERROR': 'LAN_EXP-2024',
    'IMG_BASE64_EMPTY': 'LAN_EXP-4008',
    'FACE_ID_ILLEGAL': 'LAN_EXP-4006',
    'FACE_ID_EXISTS': 'LAN_EXP-4007',
    'FACE_ID_NOT_EXISTS': 'LAN_EXP-4017',
    'PERSON_NO_FACE_ID': 'LAN_EXP-4031',
    'IS_EASY_WAY_ILLEGAL': 'LAN_EXP-4009',
    'IMG_INCOMPLETE': 'LAN_EXP-4035',
    'IMG_FORMAT_NOT_SUPPORTED': 'LAN_EXP-2218',
    'IMG_PARSE_ERROR': 'LAN_EXP-4011',
    'IMG_RESOLUTION_TOO_HIGH': 'LAN_EXP-2241',
    'MAX_FACES_REACHED': 'LAN_EXP-4012',
    'FACE_NOT_DETECTED': 'LAN_EXP-8006',
    'MULTIPLE_FACES_DETECTED': 'LAN_EXP-8007',
    'FACE_TOO_SMALL': 'LAN_EXP-8010',
    'FACE_TOO_LARGE': 'LAN_EXP-8013',
    'FEATURE_EXTRACTION_FAILED': 'LAN_EXP-8011',
    'FEATURE_EXTRACTION_ERROR': 'LAN_EXP-8012',
    'FACE_ANGLE_TOO_LARGE': 'LAN_EXP-8014',
    'FACE_LIGHT_ERROR': 'LAN_EXP-8015',
    'FACE_BLURRY': 'LAN_EXP-8016',
    'FACE_LIGHT_UNEVEN': 'LAN_EXP-8017',
    'START_TIME_PARAM_ERROR': 'LAN_EXP-3031',
    'END_TIME_PARAM_ERROR': 'LAN_EXP-3032',
    'START_TIME_FORMAT_ERROR': 'LAN_EXP-3033',
    'END_TIME_FORMAT_ERROR': 'LAN_EXP-3034',
    'END_TIME_LESS_THAN_START': 'LAN_EXP-3035',
    'MODEL_ILLEGAL': 'LAN_EXP-5007',
    'INTERNAL_ERROR': 'LAN_EXP-5001'  # 新增内部错误码
}
