# 验证热启动功能
print("=== 验证热启动功能 ===")
print("热启动功能已添加到mockserver.py中")
print("配置文件已添加到configs/url_config.py中")
print("\n热启动功能特点：")
print("1. 监控指定目录下的Python文件变化")
print("2. 检测到文件变化后自动重启服务器")
print("3. 可通过配置文件开启或关闭")
print("4. 可配置检测间隔和监控目录")
print("\n使用方法：")
print("1. 启动服务器：python mockserver.py")
print("2. 修改任意业务逻辑文件")
print("3. 观察控制台输出，服务器会自动重启")
print("\n配置说明：")
print("- 配置文件：configs/url_config.py")
print("- 配置项：hot_restart_config")
print("- enabled：是否启用热启动")
print("- check_interval：检测间隔（秒）")
print("- monitored_dirs：监控的目录列表")
print("- monitored_extensions：监控的文件扩展名")
print("- restart_delay：重启延迟（秒）")
print("\n热启动功能已就绪，您可以通过修改Python文件来测试！")
