Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('building_manage', '3', '值班机楼组tab', NULL, 'user_person_duty', '/', NULL, 'auth', 'admin', 0, 'building_manage', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);
Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('class_batch_adjust_plan_btn', '3', '批量计划调整', NULL, 'user_person_duty', '/v1/dutyManagement/batch/update', NULL, 'auth', 'admin', 0, 'class_batch_adjust_plan_btn', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);
Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('class_edit_btn', '3', '排班管理-编辑排班', NULL, 'user_person_duty', '/v1/dutyManagement/batch/update', NULL, 'auth', 'admin', 0, 'class_edit_btn', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);
Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('class_one_day_conf_btn', '3', '单日排期配置', NULL, 'user_person_duty', '/v1/dutyManagement/singleDay/add', NULL, 'auth', 'admin', 0, 'class_one_day_conf_btn', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);
Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('class_time_add_btn', '3', '值班时间管理-新增', NULL, 'user_person_duty', '/v1/dutyPeriodConfig/special/add', NULL, 'auth', 'admin', 0, 'class_time_add_btn', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);
Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('class_time_config_btn', '3', '配置常规值班', NULL, 'user_person_duty', '/v1/dutyPeriodConfig/general/alter', NULL, 'auth', 'admin', 0, 'class_time_config_btn', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);
Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('class_time_delete_btn', '3', '值班时间管理-删除', NULL, 'user_person_duty', '/v1/dutyPeriodConfig/special/delete', NULL, 'auth', 'admin', 0, 'class_time_delete_btn', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);
Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('class_time_order_scheduling_btn', '3', '值班时间管理-排班', NULL, 'user_person_duty', '/page-drump', NULL, 'auth', 'admin', 0, 'class_time_order_scheduling_btn', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);
Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('class_time_record_list_btn', '3', '调整记录查询', NULL, 'user_person_duty', '/v1/dutyPeriodConfig/adjustmentRecord/list', NULL, 'auth', 'admin', 0, 'class_time_record_list_btn', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);
Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('class_time_update_btn', '3', '值班时间管理-编辑', NULL, 'user_person_duty', '/v1/dutyPeriodConfig/special/update', NULL, 'auth', 'admin', 0, 'class_time_update_btn', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);
Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('duty_building_add', '3', '值班机楼组-新增', NULL, 'user_person_duty', '/', NULL, 'auth', 'admin', 0, 'duty_building_add', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);
Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('duty_building_delete', '3', '值班机楼组-删除', NULL, 'user_person_duty', '/', NULL, 'auth', 'admin', 0, 'duty_building_delete', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);
Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('duty_building_edit', '3', '值班机楼组-编辑', NULL, 'user_person_duty', '/', NULL, 'auth', 'admin', 0, 'duty_building_edit', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);
Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('duty_building_export', '3', '值班机楼组-导出', NULL, 'user_person_duty', '/', NULL, 'auth', 'admin', 0, 'duty_building_export', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);
Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('group_add_btn', '3', '值班组管理-新增', NULL, 'user_person_duty', '/v1/dutyGroup/add', NULL, 'auth', 'admin', 0, 'group_add_btn', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);
Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('group_delete_btn', '3', '值班组管理-删除', NULL, 'user_person_duty', '/v1/dutyGroup/delete', NULL, 'auth', 'admin', 0, 'group_delete_btn', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);
Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('group_export_btn', '3', '值班组管理-导出', NULL, 'user_person_duty', '/v1/dutyGroup/export', NULL, 'auth', 'admin', 0, 'group_export_btn', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);
Replace INTO wb_resources (ID, `TYPE`, NAME, description, p_id, url, icon, module, `domain`, order_key, resource_key, `method`, relation, update_date, status, `position`, hide_system, show_type, data_right_type, has_extend, layout) VALUES('group_update_btn', '3', '值班组管理-编辑', NULL, 'user_person_duty', '/v1/dutyGroup/update', NULL, 'auth', 'admin', 0, 'group_update_btn', NULL, NULL, NULL, 'enable', NULL, NULL, 'single', NULL, NULL, NULL);



replace INTO wb_role_resource(`role_id`, `resource_id`) SELECT 'f1def95e-fc74-4981-a8e0-977c55d2fa00', ID FROM wb_resources WHERE `TYPE` IN (0,1,2,3);